
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  HeroContent: 'HeroContent',
  Feature: 'Feature',
  Testimonial: 'Testimonial',
  Faq: 'Faq',
  Flight: 'Flight'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const HeroContentScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  tagline: 'tagline',
  ctaPrimaryText: 'ctaPrimaryText',
  ctaSecondaryText: 'ctaSecondaryText',
  backgroundImage: 'backgroundImage',
  planeImage: 'planeImage'
} as const

export type HeroContentScalarFieldEnum = (typeof HeroContentScalarFieldEnum)[keyof typeof HeroContentScalarFieldEnum]


export const FeatureScalarFieldEnum = {
  id: 'id',
  iconKey: 'iconKey',
  title: 'title',
  description: 'description',
  sortOrder: 'sortOrder'
} as const

export type FeatureScalarFieldEnum = (typeof FeatureScalarFieldEnum)[keyof typeof FeatureScalarFieldEnum]


export const TestimonialScalarFieldEnum = {
  id: 'id',
  name: 'name',
  role: 'role',
  text: 'text',
  rating: 'rating',
  avatar: 'avatar',
  sortOrder: 'sortOrder'
} as const

export type TestimonialScalarFieldEnum = (typeof TestimonialScalarFieldEnum)[keyof typeof TestimonialScalarFieldEnum]


export const FaqScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  sortOrder: 'sortOrder'
} as const

export type FaqScalarFieldEnum = (typeof FaqScalarFieldEnum)[keyof typeof FaqScalarFieldEnum]


export const FlightScalarFieldEnum = {
  id: 'id',
  departure: 'departure',
  arrival: 'arrival',
  departureTime: 'departureTime',
  arrivalTime: 'arrivalTime',
  departureDate: 'departureDate',
  arrivalDate: 'arrivalDate',
  duration: 'duration',
  airline: 'airline',
  price: 'price',
  seats: 'seats',
  stops: 'stops'
} as const

export type FlightScalarFieldEnum = (typeof FlightScalarFieldEnum)[keyof typeof FlightScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

